# Python_DeepLearning_Pytorch - part1

#### 딥러닝과 파이토치와 관련된 기본적인 내용을 정리하였습니다. 파이썬 딥러닝 파이토치(이경택, 방성수, 안상주 지음)을 참고하였습니다. 
#### GPU 사용을 위해서 google colab을 활용하여 작성하였습니다.

## 1. 파이토치 기초 
### 1.1 텐서
#### - 텐서란 데이터를 표현하는 단위이다. 
#### 1.1.1 Scalar

In [7]:
import torch

scalar1 = torch.tensor([1.])
print(scalar1)
print("------------------------------------------")

scalar2 = torch.tensor([3.])
print(scalar2)
print("------------------------------------------")

add_scalar = scalar1 + scalar2
print(add_scalar)
print("------------------------------------------")

sub_scalar = scalar1 - scalar2
print(sub_scalar)
print("------------------------------------------")

mul_scalar = scalar1 * scalar2
print(mul_scalar)
print("------------------------------------------")

div_scalar = scalar1 / scalar2
print(div_scalar)
print("------------------------------------------")

print(torch.add(scalar1, scalar2))
print("------------------------------------------")

print(torch.sub(scalar1, scalar2))
print("------------------------------------------")

print(torch.mul(scalar1, scalar2))
print("------------------------------------------")

print(torch.div(scalar1, scalar2))
print("------------------------------------------")


tensor([1.])
------------------------------------------
tensor([3.])
------------------------------------------
tensor([4.])
------------------------------------------
tensor([-2.])
------------------------------------------
tensor([3.])
------------------------------------------
tensor([0.3333])
------------------------------------------
tensor([4.])
------------------------------------------
tensor([-2.])
------------------------------------------
tensor([3.])
------------------------------------------
tensor([0.3333])
------------------------------------------


#### 1.1.2 Vector

In [10]:
vector1 = torch.tensor([1.,2.,3.])
print(vector1)
print("------------------------------------------")

vector2 = torch.tensor([4.,5.,6.])
print(vector2)
print("------------------------------------------")

add_vector = vector1 + vector2
print(add_vector)
print("------------------------------------------")

sub_vector = vector1 - vector2
print(sub_vector)
print("------------------------------------------")

mul_vector = vector1 * vector2
print(mul_vector)
print("------------------------------------------")

div_vector = vector1 / vector2
print(div_vector)
print("------------------------------------------")

print(torch.add(vector1, vector2))
print("------------------------------------------")

print(torch.sub(vector1, vector2))
print("------------------------------------------")

print(torch.mul(vector1, vector2))
print("------------------------------------------")

print(torch.div(vector1, vector2))
print("------------------------------------------")

# 내적
print(torch.dot(vector1, vector2))
print("------------------------------------------")

tensor([1., 2., 3.])
------------------------------------------
tensor([4., 5., 6.])
------------------------------------------
tensor([5., 7., 9.])
------------------------------------------
tensor([-3., -3., -3.])
------------------------------------------
tensor([ 4., 10., 18.])
------------------------------------------
tensor([0.2500, 0.4000, 0.5000])
------------------------------------------
tensor([5., 7., 9.])
------------------------------------------
tensor([-3., -3., -3.])
------------------------------------------
tensor([ 4., 10., 18.])
------------------------------------------
tensor([0.2500, 0.4000, 0.5000])
------------------------------------------
tensor(32.)
------------------------------------------


#### 1.1.3 행렬

In [15]:
matrix1 = torch.tensor([[1., 2.], [3., 4.]])
print(matrix1)
print("------------------------------------------")

matrix2 = torch.tensor([[5.,6.], [7.,8.]])
print(matrix2)
print("------------------------------------------")

sum_matrix = matrix1 + matrix2
print(sum_matrix)
print("------------------------------------------")

sub_matrix = matrix1 - matrix2
print(sub_matrix)
print("------------------------------------------")

mul_matrix = matrix1 * matrix2
print(mul_matrix)
print("------------------------------------------")

div_matrix = matrix1 / matrix2
print(div_matrix)
print("------------------------------------------")

print(torch.add(matrix1, matrix2))
print("------------------------------------------")

print(torch.sub(matrix1, matrix2))
print("------------------------------------------")

print(torch.mul(matrix1, matrix2))
print("------------------------------------------")

print(torch.div(matrix1, matrix2))
print("------------------------------------------")

# 행렬곱
print(torch.matmul(matrix1, matrix2))
print("------------------------------------------")

tensor([[1., 2.],
        [3., 4.]])
------------------------------------------
tensor([[5., 6.],
        [7., 8.]])
------------------------------------------
tensor([[ 6.,  8.],
        [10., 12.]])
------------------------------------------
tensor([[-4., -4.],
        [-4., -4.]])
------------------------------------------
tensor([[ 5., 12.],
        [21., 32.]])
------------------------------------------
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])
------------------------------------------
tensor([[ 6.,  8.],
        [10., 12.]])
------------------------------------------
tensor([[-4., -4.],
        [-4., -4.]])
------------------------------------------
tensor([[ 5., 12.],
        [21., 32.]])
------------------------------------------
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])
------------------------------------------
tensor([[19., 22.],
        [43., 50.]])
------------------------------------------


#### 1.1.4 텐서
#### - 텐서는 2차원 이상의 배열이라고 생각할 수 있다.

In [19]:
tensor1 = torch.tensor([[[1., 2.], [3., 4.]], [[5., 6.], [7., 8.]]])
print(tensor1)
print("------------------------------------------")

tensor2 = torch.tensor([[[9., 10.], [11., 12]], [[13., 14.], [15., 16.]]])
print(tensor2)
print("------------------------------------------")

sum_tensor = tensor1 + tensor2
print(sum_tensor)
print("------------------------------------------")

sub_tensor = tensor1- tensor2
print(sub_tensor)
print("------------------------------------------")

mul_tensor = tensor1*tensor2
print(mul_tensor)
print("------------------------------------------")

div_tensor = tensor1 / tensor2
print(div_tensor)
print("------------------------------------------")

print(torch.add(tensor1, tensor2))
print("------------------------------------------")

print(torch.sub(tensor1, tensor2))
print("------------------------------------------")

print(torch.mul(tensor1, tensor2))
print("------------------------------------------")

print(torch.div(tensor1, tensor2))
print("------------------------------------------")

# 텐서 행렬 곱
print(torch.matmul(tensor1, tensor2))
print("------------------------------------------")

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])
------------------------------------------
tensor([[[ 9., 10.],
         [11., 12.]],

        [[13., 14.],
         [15., 16.]]])
------------------------------------------
tensor([[[10., 12.],
         [14., 16.]],

        [[18., 20.],
         [22., 24.]]])
------------------------------------------
tensor([[[-8., -8.],
         [-8., -8.]],

        [[-8., -8.],
         [-8., -8.]]])
------------------------------------------
tensor([[[  9.,  20.],
         [ 33.,  48.]],

        [[ 65.,  84.],
         [105., 128.]]])
------------------------------------------
tensor([[[0.1111, 0.2000],
         [0.2727, 0.3333]],

        [[0.3846, 0.4286],
         [0.4667, 0.5000]]])
------------------------------------------
tensor([[[10., 12.],
         [14., 16.]],

        [[18., 20.],
         [22., 24.]]])
------------------------------------------
tensor([[[-8., -8.],
         [-8., -8.]],

        [[-8., 

### 1.2 Autograd
#### - 파이토치를 이용해 코드를 작성할 때  Back Propagation을 이용해 파라미터를 업데이트하는 방법은 Autograd 방식으로 쉽게 구현할 수 있도록 설정돼 있다.

In [25]:
import torch

if torch.cuda.is_available():   #### torch를 이용할 때 gpu를 활용할 수 있는 지 확인
  DEVICE = torch.device('cuda')
else:
  DEVICE = torch.devicd('cpu')

BATCH_SIZE = 64    #### 파라미터를 업데이트할 때 계산되는 데이터의 개수 / BATCH_SIZE 수만큼 출력된 결괏값에 대한 오찻값을 계산
INPUT_SIZE = 1000  #### 딥러닝 모델에서 INPUT의 크기, 입력층의 노드 수 / BATCH_SIZE가 64이므로 1000 크기의 벡터 값을 64개 이용한다는 의미 / (64, 1000)
HIDDEN_SIZE = 100  #### 입력층의 노드 수
OUTPUT_SIZE = 10    #### 최종적으로 출력되는 벡터의 크기 

x = torch.randn(BATCH_SIZE, INPUT_SIZE, device = DEVICE, dtype=torch.float, requires_grad=False) # input 이므로 gradient 계산이 필요 없음 / 파라미터 업데이트를 위해 gradient를 사용!
y = torch.randn(BATCH_SIZE, OUTPUT_SIZE, device = DEVICE, dtype=torch.float, requires_grad=False) 
w1 = torch.randn(INPUT_SIZE, HIDDEN_SIZE, device = DEVICE, dtype = torch.float, requires_grad=True)
w2 = torch.randn(HIDDEN_SIZE, OUTPUT_SIZE, device = DEVICE, dtype=torch.float, requires_grad=True)

learning_rate = 1e-6
for t in range(1,501):
  y_pred = x.mm(w1).clamp(min = 0).mm(w2) #### clamp(min = 0) - RELU와 같은 역할을 하는 비선형 함수

  loss = (y_pred - y).pow(2).sum()
  if t % 100 == 0: 
    print('Iteration: ', t, 'LOSS: ', loss.item())
  
  loss.backward()    #### 각 파라미터에 대해 Gradient를 계산하고 이를 통해 Back Propagation을 진행

  with torch.no_grad():    #### 각 파리미터 값에 대해 gradient 계산한 결과를 이용해 파라미터 값을 업데이트 할 때는 해당 시점의 gradient 값을 고정한 후 업데이트를 진행
    w1 -= learning_rate * w1.grad    #### gradient 업데이트
    w2 -= learning_rate * w2.grad

    w1.grad.zero_()    #### gradient를 초기화 해 다음 반복문을 진행할 수 있도록 gradient 값을 0으로 설정
    w2.grad.zero_()


Iteration:  100 LOSS:  604.5242919921875
Iteration:  200 LOSS:  3.5456395149230957
Iteration:  300 LOSS:  0.04190492630004883
Iteration:  400 LOSS:  0.0008806560072116554
Iteration:  500 LOSS:  9.233901801053435e-05
